/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jtdog;

import java.util.Set;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
public class JTDogPlugin implements Plugin<Project> {
    public void apply(final Project project) {
        registerTasks(project);
        // Register a task
        /*Set<Project> subProjects = project.getSubprojects();
        if (!subProjects.isEmpty()) {
            // registerTasks(project);
            // } else {
            for (Project subProject : subProjects) {
                registerTasks(subProject);
            }
        }*/

    }

    private void registerTasks(Project project) {
        project.getTasks().register("sniff", SniffTask.class, task -> {
            if (project.getTasks().findByPath("testClasses") != null) {
                task.dependsOn(project.getTasks().findByPath("testClasses"));
            }
            /*
             * if (project.getTasks().findByPath("compileTestJava") != null) {
             * task.dependsOn(project.getTasks().findByPath("compileTestJava")); }
             */
            task.setProject(project);
            task.setDescription("Detects Java test smells.");
            task.doLast(s -> System.out.println("Done."));
        });

        project.getTasks().register("detectDependentTests", DetectDependentTestsTask.class, task ->
        {
            task.setProject(project);
            task.setDescription("Do not use.");
        });
    }

}
