/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JTDog;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.GradleException;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.SourceSetContainer;

/**
 * A simple 'hello world' plugin.
 */
public class JTDogPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("greentest", GreenTest.class , task -> {
            
            task.doFirst(s -> {
                if(!project.hasProperty("JTDog.testDirs")){
                    //final SourceSet test = ((SourceSetContainer) project.getProperties().get("sourceSets")).getByName("test");
                    throw new GradleException("Please set the JTDog.testDirs property.");
                }
                System.out.println("ok");
            });

            task.setProject(project);

            task.doLast(s -> System.out.println("Done."));
        });
    }
}
