/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jtdog;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
public class JTDogPlugin implements Plugin<Project> {
    public void apply(final Project project) {
        // Register a task
        project.getTasks().register("sniff", SniffTask.class, task -> {
            task.dependsOn("compileJava");
            task.dependsOn("compileTestJava");
            task.setProject(project);
            task.setDescription("Detects Java test smells.");
            task.doLast(s -> System.out.println("Done."));
        });
    }
}
